"""empty message

Revision ID: 237734483700
Revises: 7211ceddf330
Create Date: 2018-08-04 15:23:51.049893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '237734483700'
down_revision = '7211ceddf330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('votes', 'created_date1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('created_date1', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('votes', 'created_date')
    # ### end Alembic commands ###
