"""empty message

Revision ID: 7211ceddf330
Revises: 4eb137711a67
Create Date: 2018-08-04 15:23:06.877155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7211ceddf330'
down_revision = '4eb137711a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('created_date1', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('votes', 'created_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('votes', 'created_date1')
    # ### end Alembic commands ###
